ú2:11:320:15:28:29.906 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
ú2:11:320:15:28:29.915 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:278) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
ú2:11:320:15:28:30.412 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - Unknown table 'schedule' in field list
ú2:11:320:15:28:30.412 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
ú2:11:320:18:47:54.732 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
ú2:11:320:18:47:54.744 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:278) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
ú2:11:320:18:47:55.052 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - Unknown table 'schedule' in field list
ú2:11:320:18:47:55.052 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:325:17:19:37.362 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:325:17:19:37.373 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:279) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:325:17:19:38.004 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:325:17:19:38.004 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:325:17:20:39.298 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:325:17:20:39.306 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:279) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:325:17:20:39.896 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:325:17:20:39.896 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:326:10:55:27.271 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:326:10:55:27.281 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:326:10:55:31.205 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:326:10:55:31.206 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
